packages:
  - 'apps/*'
  - 'libs/post/*'
  - 'libs/shared/*'
  - 'tools/*'
  - 'web'
  - 'web-e2e'
catalog:
  react-native: '^0.79.5'
  '@nestjs/common': '^11.0.0'
  '@nestjs/core': '^11.0.0'
  '@nestjs/platform-express': '^11.0.0'
  '@nestjs/cqrs': '^11.0.3'
  '@nestjs-cls/transactional': '^3.0.3'
  zod: '3.24.3'
catalogs:
  react19:
    react: '19.0.0'
    react-dom: '19.0.0'
    '@types/react': '~19.0.14'
    '@types/react-dom': '^19.0.4'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - 'esbuild'
  - 'nx'
