packages:
  - apps/*
  - libs/ui/*
  - tools/*
  - libs/shared/*
  - libs/user/*
  - libs/job/events/*
  - libs/email/*
  - libs/auth/*
  - libs/post/*
  - libs/jobs/events/*
  - libs/database/*
  - libs/api/*

catalog:
  '@keyv/redis': ^5.0.0
  '@radix-ui/react-icons': 1.3.2
  '@react-email/components': ^0.3.2
  '@tanstack/react-query': ^5.83.0
  '@types/serialize-javascript': ^5.0.4
  bcryptjs: ^3.0.2
  cache-manager: ^7.0.1
  cacheable: ^1.10.3
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: ^1.1.1
  keyv: ^5.4.0
  lucide-react: 0.525.0
  motion: ^12.23.9
  radix-ui: 1.4.2
  react-hook-form: ^7.61.1
  react-qr-code: ^2.0.18
  recharts: 2.15.4
  rxjs: ^7.8.2
  serialize-javascript: ^6.0.2
  sonner: ^2.0.6
  tailwindcss-animate: ^1.0.7
  ua-parser-js: ^2.0.4
  uuid: ^11.1.0
  validated-extendable: ^7.3.0

catalogs:
  auth:
    better-auth: ^1.3.3
  drizzle:
    '@testcontainers/postgresql': ^11.4.0
    '@types/pg': ^8.15.4
    '@vercel/postgres': ^0.10.0
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.3
    drizzle-seed: ^0.3.1
    drizzle-zod: ^0.8.2
    pg: ^8.16.3
    testcontainers: ^11.4.0
  expo:
    '@better-auth/expo': ^1.3.4
    '@expo/metro-config': ^0.20.17
    '@expo/metro-runtime': ~5.0.4
    expo: 53.0.9
    expo-constants: 17.1.6
    expo-dev-client: 5.1.8
    expo-linking: 7.1.5
    expo-router: 5.0.7
    expo-secure-store: 14.2.3
    expo-splash-screen: 0.30.8
    expo-status-bar: 2.2.3
    expo-system-ui: ~5.0.10
    expo-web-browser: 14.1.6
  nestjs:
    '@nestjs-cls/transactional': ^3.1.0
    '@nestjs-cls/transactional-adapter-drizzle-orm': ^1.2.0
    '@nestjs-modules/mailer': ^2.0.2
    '@nestjs/cache-manager': ^3.0.1
    '@nestjs/common': ^11.1.5
    '@nestjs/core': ^11.1.5
    '@nestjs/cqrs': ^11.0.3
    '@nestjs/microservices': ^11.1.5
    '@nestjs/testing': ^11.1.5
    nestjs-cls: ^6.0.1
  next:
    '@next/eslint-plugin-next': ^15.4.3
    next: ~15.4.3
    next-safe-action: ^8.0.8
    next-themes: ^0.4.6
  react-native:
    '@legendapp/list': ^1.1.4
    nativewind: ~4.1.23
    react-native: 0.79.5
    react-native-gesture-handler: ~2.25.0
    react-native-reanimated: ~3.18.0
    react-native-safe-area-context: ~5.4.1
    react-native-screens: ~4.11.1
  react19:
    '@types/react': ^19.0.14
    '@types/react-dom': ^19.1.6
    react: ^19.0.0
    react-dom: ^19.0.0
  tailwind3:
    tailwind-merge: ^2.6.0
    tailwindcss: 3.4.3
  trpc:
    '@trpc/client': 11.4.3
    '@trpc/server': 11.4.3
    '@trpc/tanstack-react-query': 11.4.3
    superjson: ^2.2.2
    trpc-to-openapi: ^2.3.2
    trpc-ui: ^1.0.15
  zod3:
    '@anatine/zod-mock': ^3.14.0
    '@t3-oss/env-nextjs': ^0.13.8
    zod: ^3.25.76

ignore-workspace-root-check: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bufferutil
  - core-js
  - cpu-features
  - esbuild
  - nx
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
